name: Floodgate-Skript
version: ${project.version}
main: com.github.camotoy.floodgate_skript.FloodgateSkript
api-version: 1.15
authors: [Camotoy]
depend: [floodgate-bukkit, Skript]
softdepend: [Geyser-Spigot]
